### ISSUE TITLE
Reprise du developpement

### ISSUE THREAD

**Issue by zuygui** [mistersouls/ba#1]
Bonjour, je souhaiterais reprendre le développement de ba, le faire changer de nom afin de le développer un max. Puis-je avoir votre accord ? vous serez mentionné en tant que créateur de la souche du langage.

**Comment by mistersouls** [comment]
Bonjour @Zuygui , vous pouvez directement contribuer dessus si ça vous intéresse :) .
Let discuss in english for the next comments.
